spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.tool.hbm2ddl: DEBUG
    org.springframework.boot.context.properties: DEBUG
