spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

web3j:
  listener:
    enabled: ${WEB3J_LISTENER_ENABLED:false}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.tool.hbm2ddl: DEBUG
    org.springframework.boot.context.properties: DEBUG
