package org.privote.backend.entity.enums;

public enum SystemLogAction
{
    CREATE_ELECTION,
    UPDATE_ELECTION,
    PATCH_ELECTION,
    DELETE_ELECTION,
    DEPLOY_ELECTION,
    START_ELECTION,
    END_ELECTION,
    PUBLISH_ELECTION_RESULTS,
    CREATE_CANDIDATE,
    CREATE_CANDIDATE_BY_CIN,
    UPDATE_CANDIDATE,
    PATCH_CANDIDATE,
    DELETE_CANDIDATE,
    CREATE_PARTY,
    UPDATE_PARTY,
    PATCH_PARTY,
    DELETE_PARTY
}
